# Generated by Django 4.2.4 on 2023-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/optimized/'),
        ),
    ]
