# Generated by Django 4.2.4 on 2023-08-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default-article-image.jpg', upload_to='article_images/'),
        ),
        migrations.AddField(
            model_name='page',
            name='articles',
            field=models.ManyToManyField(blank=True, to='blog.article'),
        ),
    ]
