# Generated by Django 4.2.4 on 2023-08-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_page_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='page',
            name='youtube_link',
        ),
    ]
