# Generated by Django 4.2.4 on 2023-08-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_page_instagram_link_remove_page_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
