# Generated by Django 4.2.4 on 2023-08-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_menuitem_link_menuitem_show_in_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
