# Generated by Django 4.2.4 on 2023-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_menuitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
                ('articles', models.ManyToManyField(to='blog.article')),
            ],
        ),
    ]
