# Generated by Django 4.2.4 on 2023-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_realestatepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('standard', 'Standard Article'), ('real_estate', 'Real Estate Gallery')], default='standard', max_length=20),
        ),
    ]
