# Generated by Django 4.2.4 on 2023-09-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestatepage',
            old_name='articles',
            new_name='related_articles',
        ),
    ]
